### PR TITLE
Support for Part of Speech tags counting

### PR DESCRIPTION
**Pull request by fdartayre**
Hi Alexander. Please have a look on the following pull request. 

It contains:
- A new processor that uses OpenNLP POS tagger to count the different part of speech tags (the named entity recognition processor was renamed to avoid confusion between the two processors of the plugin)
- Upgrade to Elasticsearch 5.6.1
- Compatibility with Gradle 4.x
- Updated tests and README.md

### CODE REVIEW

**Comment by yehosef** [comment]
+1 - this would be great!

**Comment by spinscale** [comment]
I upgraded to ES 6.0 in the meantime... any chance for a rebase?

**Comment by fdartayre** [comment]
I will have a look on upgrading to ES 6.x as soon as possible

**Comment by ninesalt** [comment]
If this is still wanted, I added POS support in [my fork](https://github.com/ninesalt/elasticsearch-ingest-opennlp) for v6.5.4. I probably could have saved a lot of time by checking this PR and modified @fdartayre's fork before I forked the repo and added support for POS myself.  Apart from the difference in versions, my fork counts the occurence of specific words as well. For example: 
```

      "NNS": {
          "times": 1,
          "players": 3,
          "points": 1
      }, 
```

**Comment by spinscale** [comment]
@ninesalt feel free to open a PR!

**Comment by spinscale** [comment]
unfortunately this cannot be merged anymore. I do not have time to work on this. I will close this for now and hope someone opens a new PR.

**Pull request closed without merging**
